name: Azure Enterprise

resources:
  pipelines:
    - pipeline: AzureEnterprise
      source: azure-enterprise
  repositories:
    - repository: cnp-azuredevops-libraries
      type: github
      ref: refs/heads/master
      name: hmcts/cnp-azuredevops-libraries
      endpoint: 'hmcts (1)'

parameters:
  - name: overrideAction
    type: string
    default: plan
    values:
      - plan
      - apply

  - name: environment_components
    type: object
    default:
      - stage: 'dcd_cft_sandbox'
        environment: 'sbox'
        component: 'acme'
        product: 'cft-platform'
        service_connection: 'dcd-cft-sandbox'
        init_subscription: '04d27a32-7a07-48b3-95b8-3c8691e1a263'
        dependsOn: 'Precheck'

variables:
  - name: timeoutInMinutes
    value: 60
  - name: agentPool
    value: ubuntu-latest
  - template: vars/input-variables.yaml@cnp-azuredevops-libraries


stages:
  - stage: Precheck
    jobs:
      - job: Precheck
        pool:
          vmImage: ${{ variables.agentPool }}
        timeoutInMinutes: ${{ variables.timeoutInMinutes }}
        steps:
          - template: steps/terraform-precheck.yaml@cnp-azuredevops-libraries
            parameters:
              keyvaultName: 'infra-vault-nonprod'
              keyvaultSecret: 'azure-devops-token'
              serviceConnection: 'DCD-CFT-Sandbox'

          # - template: steps/pipeline-tests-jest.yaml@cnp-azuredevops-libraries
          #   parameters:
          #     workingDirectory: $(Pipeline.Workspace)/s/azure-enterprise/tests
          #     junit_output_dir: $(Pipeline.Workspace)/s/azure-enterprise/tests/junit
          #     environment: prod
          #     product: ${{ variables.product }}
          #     test_title: 'Naming conventions'
          #     test_pattern: namingConventions.test.js
  # - ${{ each deployment in parameters.environment_components }}:
  #     - stage: ${{ deployment.stage }}
  #       dependsOn: ${{ deployment.dependsOn }}
  #       jobs:
  #         - job: TerraformPlanApply
  #           pool:
  #             vmImage: ${{ variables.agentPool }}
  #           timeoutInMinutes: ${{ variables.timeoutInMinutes }}
  #           steps:
  #             - template: steps/terraform.yaml@cnp-azuredevops-libraries
  #               parameters:
  #                 overrideAction: ${{ parameters.overrideAction }}
  #                 environment: ${{ deployment.environment }}
  #                 component: ${{ deployment.component }}
  #                 serviceConnection: ${{ deployment.service_connection }}
  #                 terraformInitSubscription: ${{ deployment.init_subscription }}
  #                 product: ${{ deployment.product }}
