name: test
trigger:
  batch: true
  branches:
    include:
      - main

schedules:
- cron: "0 7 * * *" # first day at 8am
  displayName: Every day at 8am GMT
  branches:
    include:
    - main
  always: true

resources:
  repositories:
    - repository: cnp-azuredevops-libraries
      type: github
      ref: refs/heads/master
      name: hmcts/cnp-azuredevops-libraries
      endpoint: 'hmcts'

parameters:
  - name: overrideAction
    type: string
    default: plan
    values:
      - plan
      - apply


variables:
  - name: timeoutInMinutes
    value: 60
  - name: agentPool
    value: ubuntu-latest
  - name: product
    value: enterprise
  - template: vars/input-variables.yaml@cnp-azuredevops-libraries


stages:
  - stage: TestWorkloadIdentity
    jobs:
      - job: TestWorkloadIdentity
        pool:
          vmImage: ${{ variables.agentPool }}
        timeoutInMinutes: ${{ variables.timeoutInMinutes }}
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'Demo'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                echo "Testing Workload Identity"
                az login --identity
                az account show
                az group list --output table

