name: Azure Enterprise
trigger:
  batch: true
  branches:
    include:
      - main

resources:
  repositories:
    - repository: cnp-azuredevops-libraries
      type: github
      ref: refs/heads/master
      name: hmcts/cnp-azuredevops-libraries
      endpoint: 'hmcts (1)'

parameters:
  - name: overrideAction
    type: string
    default: plan
    values:
      - plan
      - apply

  - name: environment_components
    type: object
    default:
      - deployment: 'sandbox_enterprise'
        environment: 'sandbox'
        component: 'enterprise'
        service_connection: 'GA-development-tenant'
        init_subscription: '55922b0d-5c33-467f-91b9-42c4059d310c'
        dependsOn: 'Precheck'
      - deployment: 'prod_enterprise'
        environment: 'prod'
        component: 'enterprise'
        service_connection: 'GA'
        init_subscription: 04d27a32-7a07-48b3-95b8-3c8691e1a263
        dependsOn: 'sandbox_enterprise'

variables:
  - name: timeoutInMinutes
    value: 60
  - name: agentPool
    value: ubuntu-latest
  - name: product
    value: enterprise
  - template: vars/input-variables.yaml@cnp-azuredevops-libraries


stages:
  - stage: Precheck
    jobs:
      - job:
        pool:
          vmImage: ${{ variables.agentPool }}
        timeoutInMinutes: ${{ variables.timeoutInMinutes }}
        steps:
          - template: steps/terraform-precheck.yaml@cnp-azuredevops-libraries
            parameters:
              keyvaultName: 'infra-vault-nonprod'
              keyvaultSecret: 'azure-devops-token'
              serviceConnection: 'DCD-CFT-Sandbox'

          - script: |
              wget -O /tmp/yj https://github.com/sclevine/yj/releases/download/v5.1.0/yj-linux-amd64
              chmod +x /tmp/yj
              /tmp/yj -c < environments/sandbox/sandbox.tfvars > /tmp/variables.json
            displayName: Convert HCL to JSON

          - template: steps/pipeline-tests-jest.yaml@cnp-azuredevops-libraries
            parameters:
              workingDirectory: $(Pipeline.Workspace)/s/azure-enterprise/tests
              junit_output_dir: $(Pipeline.Workspace)/s/azure-enterprise/tests/junit
              environment: prod
              product: ${{ variables.product }}
              test_title: 'Naming conventions'
              test_pattern: namingConventions.test.ts
  - ${{ each deployment in parameters.environment_components }}:
      - stage: ${{ deployment.deployment }}
        dependsOn: ${{ deployment.dependsOn }}
        jobs:
          - job: TerraformPlanApply
            pool:
              vmImage: ${{ variables.agentPool }}
            timeoutInMinutes: ${{ variables.timeoutInMinutes }}
            steps:
              - template: steps/terraform.yaml@cnp-azuredevops-libraries
                parameters:
                  overrideAction: ${{ parameters.overrideAction }}
                  environment: ${{ deployment.environment }}
                  component: ${{ deployment.component }}
                  serviceConnection: ${{ deployment.service_connection }}
                  terraformInitSubscription: ${{ deployment.init_subscription }}
                  product: ${{ variables.product }}
