name: create-mermaid-diagram

on:
  pull_request:
  push:
    branches: [main]
    paths:
    - environments/*

jobs:
  create-mermaid-diagram:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pre-requisites
        run: |
          wget https://github.com/sclevine/yj/releases/download/v5.1.0/yj-linux-amd64 -O /usr/bin/yj
          sudo chmod +x /usr/bin/yj
          sudo apt-get install -y jq


      - name: Setup Script
        run: |
          chmod +x scripts/create-mermaid-diagram.sh

      - name: Create mermaid diagram
        run: ./scripts/create-mermaid-diagram.sh
        working-directory: ./
        shell: bash

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: environments/*
